name: Workflow CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  train_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout repository
        uses: actions/checkout@v3

      - name: 🧪 Setup Miniconda with conda.yaml
        uses: conda-incubator/setup-miniconda@v2
        with:
          environment-file: MLProject/conda.yaml
          activate-environment: mlflow-env
          auto-activate-base: false

      - name: 🧠 Confirm Python & packages
        run: |
          which python
          python --version
          pip list

      - name: Run MLflow project
        working-directory: ./MLProject
        env:
          MLFLOW_TRACKING_USERNAME: ${{ secrets.DAGSHUB_USERNAME }}
          MLFLOW_TRACKING_PASSWORD: ${{ secrets.DAGSHUB_TOKEN }}
        run: |
          mkdir -p models
          mlflow run . -P data_path=air_quality_preprocessing.csv -P model_output=models/model.pkl
